# Generated by Django 4.1.7 on 2023-03-28 04:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('code', models.CharField(default=accounts.models.generate_otp, max_length=30)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
